### ISSUE TITLE
Feature request: Rebuild job

### ISSUE THREAD

**Issue by lebe-dev** [enkron/jenkinsctl#1]
Hi

It would be great to execute rebuild for specified job.

As I see it's not possible with current implementation?

**Comment by enkron** [comment]
Hello Eugene,
Apologies for the late response.

Unfortunately the `rebuild` isn't implemented yet, but i'll try to add the feature in the near future.

Thank you for the request!

**Comment by lebe-dev** [comment]
I did little research on that topic yesterday :), rebuild plugin doesn't have API. But you have `buildWithParameters` method and information from previous build (params).

**Comment by enkron** [comment]
Hello Eugene,

it's 5 months have already passed so you're might not interested in the request but i've added `rebuild` option to the tool )

**Comment by lebe-dev** [comment]
It's awesome, thank you :)
